/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.educautecisystems.intefaz;

import java.util.List;
import org.educautecisystems.controladores.AdministradorJpaController;
import org.educautecisystems.controladores.DocenteJpaController;
import org.educautecisystems.core.Sistema;
import org.educautecisystems.entidades.Administrador;
import org.educautecisystems.entidades.Docente;

/**
 *
 * @author Shadow2012
 */
public class Ingreso extends javax.swing.JInternalFrame {
private static final int TIPO_USUARIO_ADMINISTRADOR =0;
private static final int TIPO_USUARIO_DOCENTE =1;  
    /**
     * Creates new form Ingreso
     */
    public Ingreso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private boolean comprobarUsuarioAdministrador() {
        AdministradorJpaController controladorAdministrador = 
                new AdministradorJpaController(Sistema.getEmf());
        List <Administrador> administradores = controladorAdministrador.findAdministradorEntities();
        
        for ( Administrador administrador:administradores ) {
            if ( administrador.getUsuario().equals(txtUsuario.getText()) && administrador.getContrasena().equals(txtClave.getText())) {
                return false;
            }
        }
        
        return true;
    }
    
    private boolean comprobarUsuarioDocente () {
        DocenteJpaController controladorDocente = new DocenteJpaController(Sistema.getEmf());
        List <Docente> docentes = controladorDocente.findDocenteEntities();
        
        for ( Docente docente:docentes ) {
            if ( docente.getUsuario().equals(txtUsuario.getText()) && docente.getContrasena().equals(txtClave.getText())) {
                return false;
            }
        }
        return true;  
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ButtonIngreso = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        tipoUsuarioCombobox = new javax.swing.JComboBox();

        setTitle("Ingreso Personal");

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel1.setText("EducaUteciSystems");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Clave:");

        ButtonIngreso.setText("Ingresar");
        ButtonIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIngresoActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo:");

        tipoUsuarioCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admistrador", "Docente" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(ButtonIngreso)
                                .addGap(18, 18, 18)
                                .addComponent(buttonCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsuario)
                                    .addComponent(txtClave)
                                    .addComponent(tipoUsuarioCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipoUsuarioCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonIngreso)
                    .addComponent(buttonCancelar))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIngresoActionPerformed
        
       if ( txtUsuario.getText().isEmpty() || new String(txtClave.getPassword()).isEmpty()) { 
            Sistema.mostrarMensajeError("Por favor llene todos los campos.");
            return;
        }
       
//        int idTipoUsuario = tipoUsuarioCombobox.getSelectedIndex();
//        
//        if ( idTipoUsuario == TIPO_USUARIO_ADMINISTRADOR ) {
//            if ( !comprobarUsuarioAdministrador() ) {
//                Sistema.mostrarMensajeError("Administrador ya existe.");
//                return;
//            }
//            
//            Administrador nuevoAdministrador = new Administrador();
//            
//            nuevoAdministrador.setUsuario(txtNombre.getText());
//            nuevoAdministrador.setContrasena(new String(txtClave.getPassword()));
//            
//            AdministradorJpaController controlandorAdministrador = 
//                    new AdministradorJpaController(Sistema.getEmf());
//            
//            try {
//                controlandorAdministrador.create(nuevoAdministrador);
//            } catch ( Exception e ) {
//                Sistema.mostrarMensajeError("No se pudo crear el nuevo usuario.");
//            }
//            
//            Sistema.mostrarMensajeInformativo("Se ha ingresado satisfactoriamente el usuario.");
//            this.setVisible(false);
//            this.dispose();
//            
//        } else if ( idTipoUsuario == TIPO_USUARIO_DOCENTE ) {
//            if ( !comprobarUsuarioDocente() ) {
//                Sistema.mostrarMensajeError("Docente ya existe.");
//                return;
//            }
//            Docente nuevoDocente = new Docente();
//            
//            nuevoDocente.setUsuario(txtNombre.getText());
//            nuevoDocente.setContrasena(new String(txtClave.getPassword()));
//            ObjComboBoxMateria materiaActual = (ObjComboBoxMateria) jComboBoxMateria.getSelectedItem();
//            nuevoDocente.setMateria(materiaActual.getMateria());          
//            DocenteJpaController controladorDocente = new DocenteJpaController(Sistema.getEmf());
//            
//            try {
//                controladorDocente.create(nuevoDocente);
//            } catch ( Exception e ) {
//                Sistema.mostrarMensajeError("No se pudo crear el nuevo usuario.");
//            }
//            
//            Sistema.mostrarMensajeInformativo("Se ha ingresado satisfactoriamente el usuario.");
//            this.setVisible(false);
//            this.dispose();
//        } else {
//            Sistema.mostrarMensajeError("Tipo de usuario no soportado.");
//        }   
       
    }//GEN-LAST:event_ButtonIngresoActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonIngreso;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox tipoUsuarioCombobox;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
