/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.educautecisystems.intefaz;
import java.util.List;
import org.educautecisystems.controladores.FacultadJpaController;
import org.educautecisystems.core.Sistema;
import org.educautecisystems.entidades.Facultad;
import org.educautecisystems.intefaz.objects.ObjComboBoxFacultad;

/**
 *
 * @author Shadow2013
 */
public class Ingreso_Facultad extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ingreso_Facultad
     */
    public Ingreso_Facultad() {
        initComponents();
        cargarFacultades();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
       private void cargarFacultades() {
        FacultadJpaController controladorFacultad = new FacultadJpaController(Sistema.getEmf());
        List<Facultad> facultades = controladorFacultad.findFacultadEntities();
        
        /* Cerrar ventana cuando no hay materias */
        if (facultades.isEmpty()) {
            Sistema.mostrarMensajeError("No se han ingresado materias.");
            this.dispose();
            return;
        }
        
        for ( Facultad facultad:facultades ) 
        {
          ComboIngTi.addItem(new ObjComboBoxFacultad(facultad));
        }
      }
     
    private boolean comprobarFacultad() {
        FacultadJpaController controladorFacultad = 
                new FacultadJpaController(Sistema.getEmf());
        List <Facultad> facultades = controladorFacultad.findFacultadEntities();
        
        for ( Facultad facultad: facultades ) {
            if ( facultad.getNombre().equals(TextIngreso.getText()) ) {
                return false;
            }
        }
        
        return true;
    }
    
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TextIngreso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ButtonIngreso = new javax.swing.JButton();
        ComboIngTi = new javax.swing.JComboBox();

        setTitle("Ingreso de Nueva Facultad");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Ingreso de Nueva Facultad");

        jButCancelar.setText("Cancelar");
        jButCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCancelarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Facultades Existentes");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Ingrese Nuevo:");

        ButtonIngreso.setText("Ingresar");
        ButtonIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIngresoActionPerformed(evt);
            }
        });

        ComboIngTi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ButtonIngreso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButCancelar)
                                .addGap(8, 8, 8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboIngTi, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ComboIngTi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonIngreso)
                    .addComponent(jButCancelar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIngresoActionPerformed
                   if ( TextIngreso.getText().isEmpty()) {
                        Sistema.mostrarMensajeError("Por favor llene el campo.");
                        return;
                    }
        
                    if ( !comprobarFacultad() ) {
                            Sistema.mostrarMensajeError("La Facultad ya existe.");
                            return;
                        }
        
                    Facultad nuevoFacultad = new Facultad();
        
                    nuevoFacultad.setNombre(TextIngreso.getText());
        
                    FacultadJpaController controlandorFacultad =
                            new FacultadJpaController(Sistema.getEmf());
        
                    try {
                            controlandorFacultad.create(nuevoFacultad);
                        } catch ( Exception e ) {
                            Sistema.mostrarMensajeError("No se pudo crear la nueva facultad.");
                        }
        
                    Sistema.mostrarMensajeInformativo("Se ha ingresado satisfactoriamente la facultad.");
             
    }//GEN-LAST:event_ButtonIngresoActionPerformed

    private void jButCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonIngreso;
    private javax.swing.JComboBox ComboIngTi;
    private javax.swing.JTextField TextIngreso;
    private javax.swing.JButton jButCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
