/*
 *  ChatServerInterface.java
 *  Copyright (C) 2012  Guillermo Pazos <shadowguiller@gmail.com>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.educautecisystems.intefaz;
import java.util.List;
import org.educautecisystems.controladores.FacultadJpaController;
import org.educautecisystems.controladores.exceptions.NonexistentEntityException;
import org.educautecisystems.core.Sistema;
import org.educautecisystems.entidades.Facultad;
import org.educautecisystems.intefaz.mantenimiento.FacultadMantenimiento;
import org.educautecisystems.intefaz.objects.ObjComboBoxFacultad;

/**
 *
 * @author Shadow2013
 */
public class Ingreso_Facultad extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ingreso_Facultad
     */
    public Ingreso_Facultad() {
        initComponents();
        cargarFacultades();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
       private void cargarFacultades() {
        FacultadJpaController controladorFacultad = new FacultadJpaController(Sistema.getEmf());
        List<Facultad> facultades = controladorFacultad.findFacultadEntities();
        
        /* Cerrar ventana cuando no hay materias */
        if (facultades.isEmpty()) {
            Sistema.mostrarMensajeError("No se han ingresado materias.");
            this.dispose();
            return;
        }
        
        for ( Facultad facultad:facultades ) 
        {
         FacultadMantenimiento administradorMantenimiento = new FacultadMantenimiento(facultad);
          ComboIngTi.addItem(administradorMantenimiento);            
//          ComboIngTi.addItem(new ObjComboBoxFacultad(facultad));
        }
      }
     
    private boolean comprobarFacultad() {
        FacultadJpaController controladorFacultad = 
                new FacultadJpaController(Sistema.getEmf());
        List <Facultad> facultades = controladorFacultad.findFacultadEntities();
        
        for ( Facultad facultad: facultades ) {
            if ( facultad.getNombre().equals(TextIngreso.getText()) ) {
                return false;
            }
        }
        
        return true;
    }
    
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TextIngreso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ButtonIngreso = new javax.swing.JButton();
        ComboIngTi = new javax.swing.JComboBox();
        jbModif = new javax.swing.JButton();
        jbElim = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTexModi = new javax.swing.JTextField();

        setTitle("Ingreso de Nueva Facultad");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Ingreso de Nueva Facultad");

        jButCancelar.setText("Cancelar");
        jButCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCancelarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Facultades Existentes");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Ingrese Nuevo:");

        ButtonIngreso.setText("Ingresar");
        ButtonIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIngresoActionPerformed(evt);
            }
        });

        ComboIngTi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        ComboIngTi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboIngTiItemStateChanged(evt);
            }
        });

        jbModif.setText("Modificar");
        jbModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModifActionPerformed(evt);
            }
        });

        jbElim.setText("Eliminar");
        jbElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbElimActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Modificar un registro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jLabel4)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ComboIngTi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextIngreso)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(0, 0, Short.MAX_VALUE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jTexModi))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 231, Short.MAX_VALUE)
                        .addComponent(ButtonIngreso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbModif)
                        .addGap(3, 3, 3)
                        .addComponent(jbElim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ComboIngTi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTexModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonIngreso)
                    .addComponent(jButCancelar)
                    .addComponent(jbModif)
                    .addComponent(jbElim))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIngresoActionPerformed
                   if ( TextIngreso.getText().isEmpty()) {
                        Sistema.mostrarMensajeError("Por favor llene el campo.");
                        return;
                    }
        
                    if ( !comprobarFacultad() ) {
                            Sistema.mostrarMensajeError("La Facultad ya existe.");
                            return;
                        }
        
                    Facultad nuevoFacultad = new Facultad();
        
                    nuevoFacultad.setNombre(TextIngreso.getText());
        
                    FacultadJpaController controlandorFacultad =
                            new FacultadJpaController(Sistema.getEmf());
        
                    try {
                            controlandorFacultad.create(nuevoFacultad);
                        } catch ( Exception e ) {
                            Sistema.mostrarMensajeError("No se pudo crear la nueva facultad.");
                        }
        
                    Sistema.mostrarMensajeInformativo("Se ha ingresado satisfactoriamente la facultad.");
                    this.dispose();
             
    }//GEN-LAST:event_ButtonIngresoActionPerformed

    private void jButCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButCancelarActionPerformed

    private void jbModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModifActionPerformed
        // TODO add your handling code here:
        //        Es para que obligue al usuario ingresar todo en los campos
        if (jTexModi.getText().isEmpty()) {
            Sistema.mostrarMensajeError("Por favor llene el campo de modificación.");
            return;
        }
        FacultadJpaController controladorFacultad = new FacultadJpaController(Sistema.getEmf());
        FacultadMantenimiento facultadMantenimiento = (FacultadMantenimiento) ComboIngTi.getSelectedItem();
        Facultad modificador = facultadMantenimiento.getFacultad();
        modificador.setNombre(jTexModi.getText());
        try {
            controladorFacultad.edit(modificador);
              Sistema.mostrarMensajeInformativo("Se a modificado la facultad con exito");      
        } catch (NonexistentEntityException ex) {
            Sistema.mostrarMensajeError("No existe la facultad actual");
        } catch (Exception ex) {
            Sistema.mostrarMensajeError("Error al modificar la facultad");
        }
        this.dispose();
    }//GEN-LAST:event_jbModifActionPerformed

    private void jbElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbElimActionPerformed
        // TODO add your handling code here:
        FacultadJpaController controladorFacultad = new FacultadJpaController(Sistema.getEmf());
        FacultadMantenimiento actual = (FacultadMantenimiento)ComboIngTi.getSelectedItem();
        try {
            controladorFacultad.destroy(actual.getFacultad().getIdFacultad());
            Sistema.mostrarMensajeInformativo("Se ha borrado safisfactoriamente la facultad");
            this.setVisible(false);
            this.dispose();
          
        } catch (NonexistentEntityException ex) {
            Sistema.mostrarMensajeError("No se puede borrar la facultad");
            return;
        }
        ComboIngTi.removeAllItems();
        List <Facultad> facultades  = controladorFacultad.findFacultadEntities();

        for (Facultad facultad:facultades) {
            FacultadMantenimiento facultadMantenimiento = new FacultadMantenimiento(facultad);
            ComboIngTi.addItem(facultadMantenimiento);
     }
    }//GEN-LAST:event_jbElimActionPerformed

    private void ComboIngTiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboIngTiItemStateChanged
        // TODO add your handling code here:
        FacultadMantenimiento facultadMantenimiento = (FacultadMantenimiento) ComboIngTi.getSelectedItem();
        jTexModi.setText(facultadMantenimiento.getFacultad().getNombre());        
    }//GEN-LAST:event_ComboIngTiItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonIngreso;
    private javax.swing.JComboBox ComboIngTi;
    private javax.swing.JTextField TextIngreso;
    private javax.swing.JButton jButCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTexModi;
    private javax.swing.JButton jbElim;
    private javax.swing.JButton jbModif;
    // End of variables declaration//GEN-END:variables
}
