/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.educautecisystems.intefaz;

import javax.swing.JFrame;

/**
 *
 * @author Shadow2012
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorioPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemIngreso = new javax.swing.JMenuItem();
        MenuItemSalir = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        MenuItemChatEst = new javax.swing.JMenuItem();
        MenuItemLisDoc = new javax.swing.JMenuItem();
        MenuItemEnInDo = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        MenuItemInSerCha = new javax.swing.JMenuItem();
        MenuItemChatDoc = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EducaUteciSystems");

        jMenu1.setText("Archivo");

        MenuItemIngreso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        MenuItemIngreso.setText("Ingresar");
        MenuItemIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemIngresoActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemIngreso);

        MenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MenuItemSalir.setText("Salir");
        MenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemSalir);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Ayuda");
        jMenuBar1.add(jMenu4);

        jMenu3.setText("Estudiante");

        MenuItemChatEst.setText("Chat");
        MenuItemChatEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemChatEstActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItemChatEst);

        MenuItemLisDoc.setText("Listado de Documentación");
        MenuItemLisDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLisDocActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItemLisDoc);

        MenuItemEnInDo.setText("Enlace Interfaz Docente");
        MenuItemEnInDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEnInDoActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItemEnInDo);

        jMenuItem4.setText("Encuesta");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Docente");

        jMenuItem6.setText("Carga de Documentos");
        jMenu2.add(jMenuItem6);

        MenuItemInSerCha.setText("Iniciar Servidor Chat");
        MenuItemInSerCha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemInSerChaActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItemInSerCha);

        MenuItemChatDoc.setText("Chat");
        MenuItemChatDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemChatDocActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItemChatDoc);

        jMenuItem7.setText("Estadistica de Encuesta");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Administración");

        jMenuItem1.setText("Nuevo Personal");
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("Mantenimieto ");
        jMenu5.add(jMenuItem2);

        jMenuItem5.setText("Configuracion");
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemIngresoActionPerformed
       Ingreso usuarios = new Ingreso();
        escritorioPrincipal.add(usuarios);
        usuarios.setVisible(true);
    }//GEN-LAST:event_MenuItemIngresoActionPerformed

    private void MenuItemEnInDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEnInDoActionPerformed
         Chat chat = new Chat();
        escritorioPrincipal.add(chat);
        chat.setVisible(true);
    }//GEN-LAST:event_MenuItemEnInDoActionPerformed

    private void MenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuItemSalirActionPerformed

    private void MenuItemChatEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemChatEstActionPerformed
        Chat chat = new Chat();
        escritorioPrincipal.add(chat);
        chat.setVisible(true);
    }//GEN-LAST:event_MenuItemChatEstActionPerformed

    private void MenuItemChatDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemChatDocActionPerformed
         Chat chat = new Chat();
        escritorioPrincipal.add(chat);
        chat.setVisible(true);
    }//GEN-LAST:event_MenuItemChatDocActionPerformed

    private void MenuItemLisDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLisDocActionPerformed
        ListadoDocumentos lis = new ListadoDocumentos();
        escritorioPrincipal.add(lis);
        lis.setVisible(true);
    }//GEN-LAST:event_MenuItemLisDocActionPerformed

    private void MenuItemInSerChaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemInSerChaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemInSerChaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemChatDoc;
    private javax.swing.JMenuItem MenuItemChatEst;
    private javax.swing.JMenuItem MenuItemEnInDo;
    private javax.swing.JMenuItem MenuItemInSerCha;
    private javax.swing.JMenuItem MenuItemIngreso;
    private javax.swing.JMenuItem MenuItemLisDoc;
    private javax.swing.JMenuItem MenuItemSalir;
    private javax.swing.JDesktopPane escritorioPrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
