/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.educautecisystems.intefaz;

import javax.swing.JFrame;

/**
 *
 * @author Shadow2012
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorioPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuItemArchivo = new javax.swing.JMenu();
        MenuItemIngreso = new javax.swing.JMenuItem();
        MenuItemSalir = new javax.swing.JMenuItem();
        MenuAyuda = new javax.swing.JMenu();
        MenuEstu = new javax.swing.JMenu();
        MenuItemChatEst = new javax.swing.JMenuItem();
        MenuItemEncuesta = new javax.swing.JMenuItem();
        MenuItemLisDoc = new javax.swing.JMenuItem();
        MenuDoce = new javax.swing.JMenu();
        MenuItemInSerCha = new javax.swing.JMenuItem();
        MenuItemChatDoc = new javax.swing.JMenuItem();
        MenuItemEstaEnc = new javax.swing.JMenuItem();
        MenuAdmi = new javax.swing.JMenu();
        MenuItemNuePer = new javax.swing.JMenuItem();
        MenuItemMan = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MenuItemIngFac = new javax.swing.JMenuItem();
        MenuItemIngMat = new javax.swing.JMenuItem();
        MenuItemIngModal = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EducaUteciSystems");

        escritorioPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        MenuItemArchivo.setText("Archivo");

        MenuItemIngreso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        MenuItemIngreso.setText("Ingresar");
        MenuItemIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemIngresoActionPerformed(evt);
            }
        });
        MenuItemArchivo.add(MenuItemIngreso);

        MenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MenuItemSalir.setText("Salir");
        MenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSalirActionPerformed(evt);
            }
        });
        MenuItemArchivo.add(MenuItemSalir);

        jMenuBar1.add(MenuItemArchivo);

        MenuAyuda.setText("Ayuda");
        jMenuBar1.add(MenuAyuda);

        MenuEstu.setText("Estudiante");

        MenuItemChatEst.setText("Chat");
        MenuItemChatEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemChatEstActionPerformed(evt);
            }
        });
        MenuEstu.add(MenuItemChatEst);

        MenuItemEncuesta.setText("Encuesta");
        MenuItemEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEncuestaActionPerformed(evt);
            }
        });
        MenuEstu.add(MenuItemEncuesta);

        MenuItemLisDoc.setText("Listado de Documentación");
        MenuItemLisDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLisDocActionPerformed(evt);
            }
        });
        MenuEstu.add(MenuItemLisDoc);

        jMenuBar1.add(MenuEstu);

        MenuDoce.setText("Docente");

        MenuItemInSerCha.setText("Iniciar Servidor Chat");
        MenuItemInSerCha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemInSerChaActionPerformed(evt);
            }
        });
        MenuDoce.add(MenuItemInSerCha);

        MenuItemChatDoc.setText("Chat");
        MenuItemChatDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemChatDocActionPerformed(evt);
            }
        });
        MenuDoce.add(MenuItemChatDoc);

        MenuItemEstaEnc.setText("Estadistica de Encuesta");
        MenuItemEstaEnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEstaEncActionPerformed(evt);
            }
        });
        MenuDoce.add(MenuItemEstaEnc);

        jMenuBar1.add(MenuDoce);

        MenuAdmi.setText("Administración");

        MenuItemNuePer.setText("Nuevo Personal");
        MenuItemNuePer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemNuePerActionPerformed(evt);
            }
        });
        MenuAdmi.add(MenuItemNuePer);

        MenuItemMan.setText("Mantenimieto ");
        MenuItemMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemManActionPerformed(evt);
            }
        });
        MenuAdmi.add(MenuItemMan);

        jMenu1.setText("Ingreso Nuevos Datos");

        MenuItemIngFac.setText("Facultad");
        MenuItemIngFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemIngFacActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemIngFac);

        MenuItemIngMat.setText("Materia");
        MenuItemIngMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemIngMatActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemIngMat);

        MenuItemIngModal.setText("Modalidad");
        MenuItemIngModal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemIngModalActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemIngModal);

        MenuAdmi.add(jMenu1);

        jMenuBar1.add(MenuAdmi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );

        escritorioPrincipal.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemIngresoActionPerformed
       Ingreso usuarios = new Ingreso();
        escritorioPrincipal.add(usuarios);
        usuarios.setVisible(true);
    }//GEN-LAST:event_MenuItemIngresoActionPerformed

    private void MenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuItemSalirActionPerformed

    private void MenuItemChatEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemChatEstActionPerformed
        Chat chat = new Chat();
        escritorioPrincipal.add(chat);
        chat.setVisible(true);
    }//GEN-LAST:event_MenuItemChatEstActionPerformed

    private void MenuItemChatDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemChatDocActionPerformed
         Chat chat = new Chat();
        escritorioPrincipal.add(chat);
        chat.setVisible(true);
    }//GEN-LAST:event_MenuItemChatDocActionPerformed

    private void MenuItemLisDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLisDocActionPerformed
        ListadoDocumentos lis = new ListadoDocumentos();
        escritorioPrincipal.add(lis);
        lis.setVisible(true);
    }//GEN-LAST:event_MenuItemLisDocActionPerformed

    private void MenuItemInSerChaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemInSerChaActionPerformed
       
    }//GEN-LAST:event_MenuItemInSerChaActionPerformed

    private void MenuItemEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEncuestaActionPerformed
        Encuesta Enc = new Encuesta();
        escritorioPrincipal.add(Enc);
        Enc.setVisible(true);
    }//GEN-LAST:event_MenuItemEncuestaActionPerformed

    private void MenuItemEstaEncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEstaEncActionPerformed
        EstadisticaEncuesta Est = new EstadisticaEncuesta();
        escritorioPrincipal.add(Est);
        Est.setVisible(true);
    }//GEN-LAST:event_MenuItemEstaEncActionPerformed

    private void MenuItemNuePerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemNuePerActionPerformed
        CrearNuevoUsuario Est = new CrearNuevoUsuario();
        escritorioPrincipal.add(Est);
        Est.setVisible(true);
    }//GEN-LAST:event_MenuItemNuePerActionPerformed

    private void MenuItemManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemManActionPerformed
        Mantenimiento Est = new Mantenimiento();
        escritorioPrincipal.add(Est);
        Est.setVisible(true);
    }//GEN-LAST:event_MenuItemManActionPerformed

    private void MenuItemIngMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemIngMatActionPerformed
        Ingreso_Materia Est = new Ingreso_Materia();
        escritorioPrincipal.add(Est);
        Est.setVisible(true);
    }//GEN-LAST:event_MenuItemIngMatActionPerformed

    private void MenuItemIngFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemIngFacActionPerformed
        Ingreso_Facultad Fac = new Ingreso_Facultad();
        escritorioPrincipal.add(Fac);
        Fac.setVisible(true);
    }//GEN-LAST:event_MenuItemIngFacActionPerformed

    private void MenuItemIngModalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemIngModalActionPerformed
        Ingreso_Modalidad Modal = new Ingreso_Modalidad();
        escritorioPrincipal.add(Modal);
        Modal.setVisible(true);
    }//GEN-LAST:event_MenuItemIngModalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAdmi;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JMenu MenuDoce;
    private javax.swing.JMenu MenuEstu;
    private javax.swing.JMenu MenuItemArchivo;
    private javax.swing.JMenuItem MenuItemChatDoc;
    private javax.swing.JMenuItem MenuItemChatEst;
    private javax.swing.JMenuItem MenuItemEncuesta;
    private javax.swing.JMenuItem MenuItemEstaEnc;
    private javax.swing.JMenuItem MenuItemInSerCha;
    private javax.swing.JMenuItem MenuItemIngFac;
    private javax.swing.JMenuItem MenuItemIngMat;
    private javax.swing.JMenuItem MenuItemIngModal;
    private javax.swing.JMenuItem MenuItemIngreso;
    private javax.swing.JMenuItem MenuItemLisDoc;
    private javax.swing.JMenuItem MenuItemMan;
    private javax.swing.JMenuItem MenuItemNuePer;
    private javax.swing.JMenuItem MenuItemSalir;
    private javax.swing.JDesktopPane escritorioPrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
